# Generated by Django 4.0.5 on 2022-06-19 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portals', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField()),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('portal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portals.portal')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='AllowMemberRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('is_registered', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('invitation_counter', models.IntegerField()),
                ('group', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('portal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portals.portal')),
            ],
            options={
                'verbose_name_plural': 'Members Registration',
                'db_table': 'allow_member_registration',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=100)),
                ('session_hash_number', models.CharField(blank=True, max_length=25, null=True)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('portal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portals.portal')),
            ],
            options={
                'verbose_name_plural': 'Analytics Members',
                'db_table': 'analytics_members',
            },
        ),
        
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['auth_user', 'is_registered', 'created_at', 'portal', 'group'], name='members_first_n_b5024d_idx'),
        ),
        migrations.AddIndex(
            model_name='allowmemberregistration',
            index=models.Index(fields=['username', 'group_id', 'is_registered'], name='allow_membe_usernam_fc9801_idx'),
        ),
    ]
